### PR TITLE
Fix - unwanted null checks in flutter 3.0

### PR DESCRIPTION
**Pull request by bssughosh**
## Developer checklist

- [x] All github actions are passing.

## For reviewers

All PR's needs at least one reviewer to be merged.

Before merge this PR confirm that it meets all requirements listed below:

- The PR has good quality code and has tests (if is the case)
- This PR is not checked with WIP on title

### CODE REVIEW

**Comment by ShadyBoukhary** [comment]
Sorry didn't see this until now. Will merge and release.

**Comment by ShadyBoukhary** [comment]
@bssughosh can you update the example to get the tests to pass?

**Comment by bssughosh** [comment]
Yes will update the example @ShadyBoukhary

**Comment by bssughosh** [comment]
@ShadyBoukhary Shall I change pedantic to flutter lints?

**Comment by ShadyBoukhary** [comment]
Yes @bssughosh

**Comment by bssughosh** [comment]
@ShadyBoukhary I have pushed the changes which should pass all the CI tests and build workflows

**Comment by ShadyBoukhary** [comment]
One is still failing @bssughosh

**Comment by ShadyBoukhary** [comment]
I think it may need to be updated to flutter_test instead of flutter

**Comment by bssughosh** [comment]
Now its passing in my local machine @ShadyBoukhary and should pass in CI too

**Review by ShadyBoukhary — APPROVED** [review]

**Comment by ShadyBoukhary** [comment]
Thanks, merging and will release shortly.

**Comment by ShadyBoukhary** [comment]
Released @bssughosh 
https://pub.dev/packages/flutter_clean_architecture

**Pull request merged**
