### PR TITLE
100% test coverage

### PR DESCRIPTION
**Pull request by ccfiel**
## Description

*...*

## Developer checklist

- [ ] All github actions are passing.

## For reviewers

All PR's needs at least one reviewer to be merged.

Before merge this PR confirm that it meets all requirements listed below:

- The PR has good quality code and has tests (if is the case)
- This PR is not checked with WIP on title

### CODE REVIEW

**Comment by ShadyBoukhary** [comment]
@ccfiel looks like there a check failing. Can you take a look?

**Comment by devwela** [comment]
@ShadyBoukhary it is now fixed. All checks have passed.

**Review by ShadyBoukhary — APPROVED** [review]

**Comment by ShadyBoukhary** [comment]
Will release shortly

**Comment by ShadyBoukhary** [comment]
Released.

**Comment by ccfiel** [comment]
thanks! :)

**Pull request merged**
