### PR TITLE
fix: fixed applications state to work with Flutter v1.12.5

### PR DESCRIPTION
**Pull request by ajzuse**

### CODE REVIEW

**Comment by ShadyBoukhary** [comment]
Hey, thanks for contributing to the package. I have a question for you.

Why did you rename `onSuspending` to `onDetached`?

**Comment by rafaelcmm** [comment]
I'm needing this PR in my project. There is anything blocking this?

**Comment by rafaelcmm** [comment]
> Hey, thanks for contributing to the package. I have a question for you.
> 
> Why did you rename `onSuspending` to `onDetached`?

Just semantic improvements with the new lifecycle name I guess

**Comment by kleberapsilva** [comment]
waiting this PR

**Comment by ShadyBoukhary** [comment]
@kleberapsilva @rafaelcmm merged. Will push build to pub.

**Pull request merged**
